Attempt_7::ImageAnalysis
const int Attempt_7.ImageAnalysis.OLD_HOUGH_MODE
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::Hough.
const int Attempt_7.ImageAnalysis.New_HOUGH_MODE
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::Hough.
int Attempt_7.ImageAnalysis.currentMode
If 0 then Old mode (top left origin), if 1 then New Hough mode( bottom Center).
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::GetHoughMode, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::Update.
const short Attempt_7.ImageAnalysis.NumberofLinesToFind
Number of lines the hough transform should find.
Referenced by Attempt_7.ImageAnalysis::FindAverages, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Initialize.
const int Attempt_7.ImageAnalysis.AccumLength
Size of the Acuumlator's lenght. Must be able to fit the largest posible value of rho. Max rho = Sqrt( ScreenHeight^2+ (ScreenWidth/2)^2), because the origin is the bottom center and the max rho is top left or right.
Referenced by Attempt_7.ImageAnalysis::Initialize.
const int Attempt_7.ImageAnalysis.AccumLengthOld
Referenced by Attempt_7.ImageAnalysis::Initialize.
const short Attempt_7.ImageAnalysis.ThetaIncrement
How big the steps are for a potiential theta. In degreees. Large values reduce computation but less acurate.
Referenced by Attempt_7.ImageAnalysis::ClearMaxInAccum, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Initialize.
const short Attempt_7.ImageAnalysis.RhoIncrement
How big the steps are for a potiential rho values. Large values reduce computation but less acurate.
Referenced by Attempt_7.ImageAnalysis::ClearMaxInAccum, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Initialize.
const short Attempt_7.ImageAnalysis.UpdateSquareDimForDrawing
Inorder to make computations go faster, not every pixels is anylzed every time. 1 out of This value squared is analzed each pass.
Referenced by Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Smooth.
const short Attempt_7.ImageAnalysis.UpdateSquareDimForAnalysis
Inorder to make drawing go faster, not every pixels is updated every time. 1 out of This value squared is updated each pass.
Referenced by Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::ShowPath, Attempt_7.ImageAnalysis::Smooth.
const int Attempt_7.ImageAnalysis.ClearArroundMaxDegree
Number of degrees around a maximum to clear around before searching the Accumulator again.
Referenced by Attempt_7.ImageAnalysis::ClearMaxInAccum.
const int Attempt_7.ImageAnalysis.ClearArroundMaxRho
Number of rho values around a maximum to clear around before searching the Accumulator again.
Referenced by Attempt_7.ImageAnalysis::ClearMaxInAccum.
const int Attempt_7.ImageAnalysis.SmoothSearchSize
Used by the smooth method. Dimension of Number of pixels to look around for the smooth function. This (values*2)^2 = number of pixels checked.
Referenced by Attempt_7.ImageAnalysis::Smooth.
bool Attempt_7.ImageAnalysis.turnIndicatorisTheta
If true then steering desisions will be based off the theta's of the hough transform.
Referenced by Attempt_7.ImageAnalysis::FindAverages, Attempt_7.ImageAnalysis::Update.
Texture2D Attempt_7.ImageAnalysis.robotCameraView
Texture object that represents the robot camera's current view.
Referenced by Attempt_7.ImageAnalysis::SetRobotCameraView, Attempt_7.ImageAnalysis::Update1.
bool [,] Attempt_7.ImageAnalysis.trueFalseMap
TrueFalse maps used for marking pixels either "good" or "bad".
Referenced by Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::Update.
bool [,] Attempt_7.ImageAnalysis.trueFalseMapB
Referenced by Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::Update.
bool [,] Attempt_7.ImageAnalysis.trueFalseMapC
Referenced by Attempt_7.ImageAnalysis::GetTrueFalseMaptoDraw, Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::Update.
int Attempt_7.ImageAnalysis.screenWidth
Screen Width of the image to analze.
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::ShowPath, Attempt_7.ImageAnalysis::Smooth, Attempt_7.ImageAnalysis::Whiteline.
int Attempt_7.ImageAnalysis.screenHeight
Screen Height of the image to analze.
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ImageAnalysis, Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::ShowPath, Attempt_7.ImageAnalysis::Smooth, Attempt_7.ImageAnalysis::Whiteline.
int Attempt_7.ImageAnalysis.turnIndication
The turn indicator measures measures how much the analysis things the robot should go right or left. Right = positive. Left = negative.
Referenced by Attempt_7.ImageAnalysis::FindAverages, Attempt_7.ImageAnalysis::GetTurnIndicator, Attempt_7.ImageAnalysis::ShowPath.
double [] Attempt_7.ImageAnalysis.houghInfo
Stores information about lines from the hough transform. each polarRho we want to find = 7 more values to store 0=slope, 1= yInt, 2=Rho, 3=Theta, 4=Xvalue, 5=Yvalue, 6= size of the bin 5 more ending values for the averages.
Referenced by Attempt_7.ImageAnalysis::FindAverages, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::GetHoughInfo, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::Initialize.
Vector3 [] Attempt_7.ImageAnalysis.houghLineStartandStopVectors
Stores vector3 locations of the beginning and end points of two lines on the screen. Was part of the old Hough system, but potientially still useful, so has not deleted. 0 = start location of line, 1 = end location ofline.
Referenced by Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::GetHoughStartandStopVectors, Attempt_7.ImageAnalysis::Initialize.
Color [,] Attempt_7.ImageAnalysis.colorArray
Color Array 2D from the robot camera that is analzed.
Referenced by Attempt_7.ImageAnalysis::GetColorMapToDraw, Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::Update, Attempt_7.ImageAnalysis::Update1.
Color [] Attempt_7.ImageAnalysis.colorArray1D
Color Array 2D from the robot camera that is analzed. Can't extract informatino directly from the robot view Texture to 2D. But have to go through 1D array.
Referenced by Attempt_7.ImageAnalysis::Initialize, Attempt_7.ImageAnalysis::Update1.
short Attempt_7.ImageAnalysis.count1A
These values are the incremented numbers used in the giant double "for-loops". The "1" values are the for the first "for-loop".
short Attempt_7.ImageAnalysis.count1B
Referenced by Attempt_7.ImageAnalysis::Smooth.
short Attempt_7.ImageAnalysis.count1C
short Attempt_7.ImageAnalysis.count1D
Referenced by Attempt_7.ImageAnalysis::ShowPath.
short Attempt_7.ImageAnalysis.count1E
Referenced by Attempt_7.ImageAnalysis::Hough.
short Attempt_7.ImageAnalysis.count2A
These values are the incremented numbers used in the giant double "for-loops". The "2" values are the for the second "for-loop".
short Attempt_7.ImageAnalysis.count2B
Referenced by Attempt_7.ImageAnalysis::Smooth.
short Attempt_7.ImageAnalysis.count2C
short Attempt_7.ImageAnalysis.count2E
Referenced by Attempt_7.ImageAnalysis::Hough.
int [] Attempt_7.ImageAnalysis.middleValues
An array of the middle clear pixels for each row. The length of the array is the number of rows = this.screenHeight.
Referenced by Attempt_7.ImageAnalysis::Initialize.
int Attempt_7.ImageAnalysis.totalWhiteCnt
Number of white pixels the "FindWhite" found.
Referenced by Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::GetWhiteCount.
short [,] Attempt_7.ImageAnalysis.accum2
The accumlator for the hough values. Each position is a hough Bin. Each bin represents a line in Cartessian cordinates. The Accumlator is basically in polar cordinates. Theta,rho.
Referenced by Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::Initialize.
short [,] Attempt_7.ImageAnalysis.accum1
Referenced by Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::Initialize.
int Attempt_7.ImageAnalysis.cntThreshold
Used by the smooth method. How many pixels must also be white in the area around a white pixel for it to be counted white.
Referenced by Attempt_7.ImageAnalysis::Smooth.
int Attempt_7.ImageAnalysis.redGood
On a scale of 0-255 how high does a pixel RGB value have to be before being declared white.
Referenced by Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Initialize.
int Attempt_7.ImageAnalysis.blueGood
Referenced by Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Initialize.
int Attempt_7.ImageAnalysis.greenGood
Referenced by Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Initialize.
int Attempt_7.ImageAnalysis.whiteParam
Sets red_good, blue_good, green_good to this value.
Referenced by Attempt_7.ImageAnalysis::Initialize.
DrawImageAnalysis Attempt_7.ImageAnalysis.drawAnalysis
The drawingImageAnalysis class handles the vertex information the shows what the robot is thinking.
Referenced by Attempt_7.ImageAnalysis::ImageAnalysis.
int Attempt_7.ImageAnalysis.countOfNewHoughSingularities
Referenced by Attempt_7.ImageAnalysis::GetSingularitiesNewHough.
int Attempt_7.ImageAnalysis.countofOldHoughSingularities
Referenced by Attempt_7.ImageAnalysis::GetSingularitesOldHough.
Attempt_7.ImageAnalysis.ImageAnalysis(Game game, Vector2 screenSize, List< Viewport > viewPortList1)
Initializes a new instance of the ImageAnalysis class.
game The game associated with the class screenSize The size of the sceen to analze viewPortList1 A list of the view ports
References Attempt_7.ImageAnalysis::drawAnalysis, Attempt_7.ImageAnalysis::NumberofLinesToFind, Attempt_7.ImageAnalysis::RhoIncrement, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::ThetaIncrement, Attempt_7.ImageAnalysis::UpdateSquareDimForAnalysis, Attempt_7.ImageAnalysis::UpdateSquareDimForDrawing.
override void Attempt_7.ImageAnalysis.Initialize()
Called when the class is initialized. Creates many of the arrays and sets many of the values.
References Attempt_7.ImageAnalysis::accum1, Attempt_7.ImageAnalysis::accum2, Attempt_7.ImageAnalysis::AccumLength, Attempt_7.ImageAnalysis::AccumLengthOld, Attempt_7.ImageAnalysis::blueGood, Attempt_7.ImageAnalysis::colorArray, Attempt_7.ImageAnalysis::colorArray1D, Attempt_7.ImageAnalysis::greenGood, Attempt_7.ImageAnalysis::houghInfo, Attempt_7.ImageAnalysis::houghLineStartandStopVectors, Attempt_7.ImageAnalysis::middleValues, Attempt_7.ImageAnalysis::NumberofLinesToFind, Attempt_7.ImageAnalysis::redGood, Attempt_7.ImageAnalysis::RhoIncrement, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::ThetaIncrement, Attempt_7.ImageAnalysis::trueFalseMap, Attempt_7.ImageAnalysis::trueFalseMapB, Attempt_7.ImageAnalysis::trueFalseMapC, Attempt_7.ImageAnalysis::whiteParam.
void Attempt_7.ImageAnalysis.Update1(GameTime gameTime1)
Stores the texture from the robot camera in a color array before the texture is disposed. Expicitly called in the SimulationMain Draw method.
gameTime1 Clock Information
References Attempt_7.ImageAnalysis::colorArray, Attempt_7.ImageAnalysis::colorArray1D, Attempt_7.ImageAnalysis::robotCameraView, Attempt_7.ImageAnalysis::TextureTo2DArray.
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.ImageAnalysis.SetRobotCameraView(Texture2D text)
Takes a 2D renderTarget/Texture and sets it as the image to analze. Explicitly called in the SimulationMain Draw Method.
text The texture to analze.
References Attempt_7.ImageAnalysis::robotCameraView.
Referenced by Attempt_7.SimulationMain::Draw.
override void Attempt_7.ImageAnalysis.Update(GameTime gameTime)
Calls the analysis methods that actually do all the work. Basically the Main function for the Image Analysis Class.
gameTime Clock Info
References Attempt_7.ImageAnalysis::colorArray, Attempt_7.ImageAnalysis::currentMode, Attempt_7.ImageAnalysis::FindWhite, Attempt_7.ImageAnalysis::Hough, Attempt_7.ImageAnalysis::ShowPath, Attempt_7.ImageAnalysis::trueFalseMap, Attempt_7.ImageAnalysis::trueFalseMapB, Attempt_7.ImageAnalysis::trueFalseMapC, Attempt_7.ImageAnalysis::turnIndicatorisTheta.
int Attempt_7.ImageAnalysis.GetWhiteCount()
References Attempt_7.ImageAnalysis::totalWhiteCnt.
Referenced by Attempt_7.DrawImageAnalysis::Draw.
double [] Attempt_7.ImageAnalysis.GetHoughInfo()
References Attempt_7.ImageAnalysis::houghInfo.
Referenced by Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::Update.
bool [,] Attempt_7.ImageAnalysis.GetTrueFalseMaptoDraw()
References Attempt_7.ImageAnalysis::trueFalseMapC.
Referenced by Attempt_7.DrawImageAnalysis::Update.
string Attempt_7.ImageAnalysis.GetHoughMode()
Gets the Hough mode. 0 = Old, 1 = New.
"Old" if in the old mode, "New" if in the new mode
References Attempt_7.ImageAnalysis::currentMode.
Referenced by Attempt_7.DrawImageAnalysis::DrawText.
Color [,] Attempt_7.ImageAnalysis.GetColorMapToDraw()
References Attempt_7.ImageAnalysis::colorArray.
int Attempt_7.ImageAnalysis.GetTurnIndicator()
Allows the SimulationMain to get the turnIndicator.
The turn Indicator
References Attempt_7.ImageAnalysis::turnIndication.
Referenced by Attempt_7.DrawImageAnalysis::Draw, Attempt_7.SimulationMain::UpDateRobotPosition.
Vector3 [] Attempt_7.ImageAnalysis.GetHoughStartandStopVectors()
References Attempt_7.ImageAnalysis::houghLineStartandStopVectors.
Referenced by Attempt_7.DrawImageAnalysis::Update.
int Attempt_7.ImageAnalysis.GetSingularitiesNewHough()
References Attempt_7.ImageAnalysis::countOfNewHoughSingularities.
Referenced by Attempt_7.DrawImageAnalysis::DrawText.
int Attempt_7.ImageAnalysis.GetSingularitesOldHough()
References Attempt_7.ImageAnalysis::countofOldHoughSingularities.
Referenced by Attempt_7.DrawImageAnalysis::DrawText.
Color [,] Attempt_7.ImageAnalysis.TextureTo2DArray(Texture2D texture, Color[] colors1D, Color[,] colors2D)
Takes a texture and makes it into a 2D color array. Passing in the arrays is faster than trying to build it each time.
texture Texture to extract color information colors1D 1D array needed for the extraction colors2D 2D array that will be returned The 2D color array of the texture color information
Referenced by Attempt_7.ImageAnalysis::Update1.
bool [,] Attempt_7.ImageAnalysis.FindWhite(Color[,] colorArray1)
Takes a 2D color array and finds the pixels that are "white".
colorArray1 The color array to find white in. The TrueFalse bool map of white pixels. True = white, False = not white.
References Attempt_7.ImageAnalysis::blueGood, Attempt_7.ImageAnalysis::greenGood, Attempt_7.ImageAnalysis::redGood, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::totalWhiteCnt, Attempt_7.ImageAnalysis::trueFalseMap.
Referenced by Attempt_7.ImageAnalysis::Update.
bool [,] Attempt_7.ImageAnalysis.Whiteline(bool[,] whitemap)
Determines if white pixels meet the Width threshold to possibly be a line. NOT IN USE RIGHT NOW********************.
whitemap The TrueFalse map of whate Pixels A truefalse map of white pixels that met the line width requirement
References Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth.
bool [,] Attempt_7.ImageAnalysis.Smooth(bool[,] original, bool[,] final)
Takes a truefalse map and for each pixel checks the other pixels around it to see if they are also white. If the number of pixels arround it that are also white is above a threshold then keep that pixel white. Meant to reduce noise in the picture. NOT IN USE RIGHT NOW********************.
original The raw truefalse map of whie pixels. final The trueFalse map to modify The truefalse map of pixels that met the threshold requirements.
References Attempt_7.ImageAnalysis::cntThreshold, Attempt_7.ImageAnalysis::count1B, Attempt_7.ImageAnalysis::count2B, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::SmoothSearchSize, Attempt_7.ImageAnalysis::UpdateSquareDimForAnalysis, Attempt_7.ImageAnalysis::UpdateSquareDimForDrawing.
bool [,] Attempt_7.ImageAnalysis.ShowPath(bool[,] blocked, bool[,] clearPath)
Find a path through the map to go through and return it as a bool map, also set the turn indicator. Based off the reactiveNavigation from the old robot code.
blocked The trueFalse map of pixels that are blocked. clearPath Blank. This map will be turned. The trueFalse map of a clear path.
References Attempt_7.ImageAnalysis::count1D, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::turnIndication, Attempt_7.ImageAnalysis::UpdateSquareDimForAnalysis.
Referenced by Attempt_7.ImageAnalysis::Update.
void Attempt_7.ImageAnalysis.FindMaxInAccumArrayOfHough(short[,] accumToAnalze, short thetaIncrement, short startIndexOfStoringHoughInfoList)
Finds Max value in Hough. Store information about that max.
accumToAnalze The accumlator of bins we want to search thetaIncrement How large is the quantitization of the theta values. startIndexOfStoringHoughInfoList What value in the Array 'HoughInfo' should we start storing information.
References Attempt_7.ImageAnalysis::currentMode, Attempt_7.ImageAnalysis::houghInfo, Attempt_7.ImageAnalysis::New_HOUGH_MODE, Attempt_7.ImageAnalysis::OLD_HOUGH_MODE, Attempt_7.ImageAnalysis::RhoIncrement.
Referenced by Attempt_7.ImageAnalysis::Hough.
void Attempt_7.ImageAnalysis.CalculateStartandStopofLine(double x1, double y1, double slope1, int startIndexforStorageArray)
Part of the old Hough system. Finds the edge values on the screen of the lines based on the slope and yInt.
slope1 Slope of the line yintercept1 YIntercept of the line startIndexforStorageArray Where to store the information in the storage array
References Attempt_7.ImageAnalysis::currentMode, Attempt_7.ImageAnalysis::houghLineStartandStopVectors, Attempt_7.ImageAnalysis::New_HOUGH_MODE, Attempt_7.ImageAnalysis::OLD_HOUGH_MODE, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth.
Referenced by Attempt_7.ImageAnalysis::Hough.
void Attempt_7.ImageAnalysis.Hough(bool[,] isLine)
For each white pixel that might be part of a line, Find all the potiential lines going through it and store each vote for that line in the accumlator's bins. Calls the methods to search through the accumlator to find the bins with the largest values.
isLine The trueFalse array of pixels that might be part of a line.
References Attempt_7.ImageAnalysis::accum1, Attempt_7.ImageAnalysis::accum2, Attempt_7.ImageAnalysis::CalculateStartandStopofLine, Attempt_7.ImageAnalysis::ClearMaxInAccum, Attempt_7.ImageAnalysis::count1E, Attempt_7.ImageAnalysis::count2E, Attempt_7.ImageAnalysis::currentMode, Attempt_7.ImageAnalysis::FindAverages, Attempt_7.ImageAnalysis::FindMaxInAccumArrayOfHough, Attempt_7.ImageAnalysis::houghInfo, Attempt_7.ImageAnalysis::New_HOUGH_MODE, Attempt_7.ImageAnalysis::NumberofLinesToFind, Attempt_7.ImageAnalysis::OLD_HOUGH_MODE, Attempt_7.ImageAnalysis::RhoIncrement, Attempt_7.ImageAnalysis::screenHeight, Attempt_7.ImageAnalysis::screenWidth, Attempt_7.ImageAnalysis::ThetaIncrement, Attempt_7.ImageAnalysis::UpdateSquareDimForAnalysis.
Referenced by Attempt_7.ImageAnalysis::Update.
void Attempt_7.ImageAnalysis.FindAverages()
Find the average theta values. Weigh them according to the rho value of each one. Make a turning desision based off the weighted thetas if turnBytheta is on.
References Attempt_7.ImageAnalysis::houghInfo, Attempt_7.ImageAnalysis::NumberofLinesToFind, Attempt_7.ImageAnalysis::turnIndication, Attempt_7.ImageAnalysis::turnIndicatorisTheta.
Referenced by Attempt_7.ImageAnalysis::Hough.
short [,] Attempt_7.ImageAnalysis.ClearMaxInAccum(short[,] accumToChange, int rho, int theta)
Clears the array arround the maximum. Gets information about the line to clear around from the 'this.houghInfo' array.
accumToChange The Accumulator to clear around degreeIncrement The theta quantitization indexOffset How far into the 'this.houghInfo' array is the data for the line we want to clear around The accumulator with the values around the max cleared.
References Attempt_7.ImageAnalysis::ClearArroundMaxDegree, Attempt_7.ImageAnalysis::ClearArroundMaxRho, Attempt_7.ImageAnalysis::RhoIncrement, Attempt_7.ImageAnalysis::ThetaIncrement.
Referenced by Attempt_7.ImageAnalysis::Hough.