Attempt_7::DrawImageAnalysis
int Attempt_7.DrawImageAnalysis.count1A
These values are part of the double for loops that reduce the computational requirements. These are the values that are incremented.
Referenced by Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle.
int Attempt_7.DrawImageAnalysis.count2A
Referenced by Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle.
int Attempt_7.DrawImageAnalysis.count1C
Referenced by Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
int Attempt_7.DrawImageAnalysis.count2C
Referenced by Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
int Attempt_7.DrawImageAnalysis.count1D
Other count usage. 1D = the number of vertexs to draw. So the number of triangels will be 1/3 this number.
Referenced by Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::drawUsingSmallerNumberofVertexs, Attempt_7.DrawImageAnalysis::InsertLine, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangleUsingIndex.
int Attempt_7.DrawImageAnalysis.screenWidth
The screenSize.
Referenced by Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.DrawImageAnalysis::DrawAnalysis, Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::LoadVertexArray, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangleUsingIndex, Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
int Attempt_7.DrawImageAnalysis.screenHeight
Referenced by Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.DrawImageAnalysis::DrawAnalysis, Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::LoadVertexArray, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangleUsingIndex, Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
int Attempt_7.DrawImageAnalysis.UpdateSquareDimForDrawing
The dimensions of the double for loops.
Referenced by Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle, Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
int Attempt_7.DrawImageAnalysis.UpdateSquareDimForAnalysis
Referenced by Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText.
int Attempt_7.DrawImageAnalysis.NumberofLinesToFind
How many lines to find.
Referenced by Attempt_7.DrawImageAnalysis::AddHoughLinesColor, Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText.
int Attempt_7.DrawImageAnalysis.ThetaIncrement
How precise the hough transform is. How large between possible values.
Referenced by Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText.
int Attempt_7.DrawImageAnalysis.RhoIncrement
Referenced by Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText.
Camera Attempt_7.DrawImageAnalysis.camera
Camera used to draw the triangles of what the robot is "thinking".
Referenced by Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::LoadVertexArray.
List<Viewport> Attempt_7.DrawImageAnalysis.viewPortList
List holding the viewports used in the simulation. This list is created in the Main simulation and then passed to this class when it is initiaized.
Referenced by Attempt_7.DrawImageAnalysis::Draw, Attempt_7.DrawImageAnalysis::DrawImageAnalysis.
BasicEffect Attempt_7.DrawImageAnalysis.basicEffects
BasicEffects for how to draw the triangles.
Referenced by Attempt_7.DrawImageAnalysis::DrawAnalysis, Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::drawUsingSmallerNumberofVertexs, Attempt_7.DrawImageAnalysis::LoadVertexArray.
SpriteFont Attempt_7.DrawImageAnalysis.arial
Font to use for drawing the debug/hough information.
Referenced by Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::Initialize.
SpriteBatch Attempt_7.DrawImageAnalysis.spriteBatch
The spriteBatch is used to draw 2D graphics.
Referenced by Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::Initialize.
VertexPositionColor [] Attempt_7.DrawImageAnalysis.vertexArray
VertexPositionColory array that stores the triangles of what the robot is "thinking". Each triangle represents 1 pixel from the robot's view. So 640*480 triangles.
Referenced by Attempt_7.DrawImageAnalysis::DrawAnalysis, Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::LoadVertexArray, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle, Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
VertexPositionColor [] Attempt_7.DrawImageAnalysis.vertexArray2
Referenced by Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.DrawImageAnalysis::drawUsingSmallerNumberofVertexs, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::InsertLine.
double [] Attempt_7.DrawImageAnalysis.houghInfo
Stores information about the hough.
Referenced by Attempt_7.DrawImageAnalysis::Draw, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::Update.
ImageAnalysis Attempt_7.DrawImageAnalysis.imageAnalysis
The image analysis object associated with this class.
Referenced by Attempt_7.DrawImageAnalysis::Draw, Attempt_7.DrawImageAnalysis::DrawImageAnalysis, Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::Update.
int [] Attempt_7.DrawImageAnalysis.vertexIndex
A list of the vertexs to draw.
Referenced by Attempt_7.DrawImageAnalysis::DrawAnalysisUsingIndex, Attempt_7.DrawImageAnalysis::Initialize, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangleUsingIndex.
List<short> Attempt_7.DrawImageAnalysis.vertexIndexList
Referenced by Attempt_7.DrawImageAnalysis::Initialize.
Vector3 [] Attempt_7.DrawImageAnalysis.houghLineStartandStopVectors
Stores vector3 locations of the beginning and end points of two lines on the screen. Was part of the old Hough system, but potientially still useful, so has not deleted. 0 = start location of line, 1 = end location ofline.
Referenced by Attempt_7.DrawImageAnalysis::AddHoughLinesColor, Attempt_7.DrawImageAnalysis::Update.
Attempt_7.DrawImageAnalysis.DrawImageAnalysis(Game game, int screenWidth, int screenHeight, int UpdateSquareDimForDrawing, int UpdateSquareDimForAnalysis, int NumberofLinesToFind, int ThetaIncrement, int RhoIncrement, List< Viewport > viewPortList, ImageAnalysis imaageanalysis)
References Attempt_7.DrawImageAnalysis::imageAnalysis, Attempt_7.DrawImageAnalysis::NumberofLinesToFind, Attempt_7.DrawImageAnalysis::RhoIncrement, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::ThetaIncrement, Attempt_7.DrawImageAnalysis::UpdateSquareDimForAnalysis, Attempt_7.DrawImageAnalysis::UpdateSquareDimForDrawing, Attempt_7.DrawImageAnalysis::viewPortList.
override void Attempt_7.DrawImageAnalysis.Initialize()
Allows the game component to perform any initialization it needs to before starting to run. This is where it can query for any required services and load content.
References Attempt_7.DrawImageAnalysis::arial, Attempt_7.DrawImageAnalysis::camera, Attempt_7.ImageAnalysis::GetHoughInfo, Attempt_7.DrawImageAnalysis::houghInfo, Attempt_7.DrawImageAnalysis::imageAnalysis, Attempt_7.DrawImageAnalysis::LoadVertexArray, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::spriteBatch, Attempt_7.DrawImageAnalysis::vertexArray2, Attempt_7.DrawImageAnalysis::vertexIndex, Attempt_7.DrawImageAnalysis::vertexIndexList.
override void Attempt_7.DrawImageAnalysis.Update(GameTime gameTime)
Allows the game component to update itself.
gameTime Provides a snapshot of timing values.
References Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.ImageAnalysis::GetHoughInfo, Attempt_7.ImageAnalysis::GetHoughStartandStopVectors, Attempt_7.ImageAnalysis::GetTrueFalseMaptoDraw, Attempt_7.DrawImageAnalysis::houghInfo, Attempt_7.DrawImageAnalysis::houghLineStartandStopVectors, Attempt_7.DrawImageAnalysis::imageAnalysis.
void Attempt_7.DrawImageAnalysis.UpdateColorArrayto3DRectangle(Color[,] c, double[] houghInfo)
Takes a 2D color array and colors the triangles. Also adds the hough lines.
c Color Array to up on the triangles vertexArray Vertex array of the triangles
References Attempt_7.DrawImageAnalysis::AddHoughLinesColor, Attempt_7.DrawImageAnalysis::count1C, Attempt_7.DrawImageAnalysis::count2C, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::UpdateSquareDimForDrawing, Attempt_7.DrawImageAnalysis::vertexArray.
override void Attempt_7.DrawImageAnalysis.Draw(GameTime gameTime)
Calls methods to draw the analysis triangles and the Debug text.
gameTime Clock Information
References Attempt_7.DrawImageAnalysis::DrawText, Attempt_7.DrawImageAnalysis::drawUsingSmallerNumberofVertexs, Attempt_7.ImageAnalysis::GetTurnIndicator, Attempt_7.ImageAnalysis::GetWhiteCount, Attempt_7.DrawImageAnalysis::houghInfo, Attempt_7.DrawImageAnalysis::imageAnalysis, Attempt_7.DrawImageAnalysis::viewPortList.
void Attempt_7.DrawImageAnalysis.UpdateBoolMapto3DRectangle(bool[,] c, double[] houghInfo)
Colors the analysis triangles based a trueFalse bool map. Also adds the Hough information If true then Blue. If false then Transparent.
c TrueFalse bool map
References Attempt_7.DrawImageAnalysis::AddHoughLinesColor, Attempt_7.DrawImageAnalysis::count1A, Attempt_7.DrawImageAnalysis::count2A, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::UpdateSquareDimForDrawing, Attempt_7.DrawImageAnalysis::vertexArray.
void Attempt_7.DrawImageAnalysis.UpdateBoolMapto3DRectangleUsingIndex(bool[,] c, double[] houghInfo)
References Attempt_7.DrawImageAnalysis::count1D, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::vertexIndex.
void Attempt_7.DrawImageAnalysis.DrawAnalysis()
Draws the Analysis Triangles stored in the 'vertexArray'.
References Attempt_7.DrawImageAnalysis::basicEffects, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::vertexArray.
void Attempt_7.DrawImageAnalysis.DrawAnalysisUsingIndex()
Draws the Analysis Triangles stored in the 'vertexArray'.
References Attempt_7.DrawImageAnalysis::basicEffects, Attempt_7.DrawImageAnalysis::count1D, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::vertexArray, Attempt_7.DrawImageAnalysis::vertexIndex.
override void Attempt_7.DrawImageAnalysis.LoadContent()
Loads the SpriteBatch Content.
void Attempt_7.DrawImageAnalysis.BuildVertexArrayforDrawingSmallerNumberofTriangles(bool[,] c, double[] houghInfo)
References Attempt_7.DrawImageAnalysis::AddHoughLinesColor, Attempt_7.DrawImageAnalysis::count1D, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::vertexArray2.
Referenced by Attempt_7.DrawImageAnalysis::Update.
void Attempt_7.DrawImageAnalysis.InsertLine(Vector3 startLocation, Vector3 endLocation, Color c)
Updates the vertex information of the triangels for a line of a particular color based off its starting and ending position.
startLocation Start position of the line. endLocation End position of the line c Color to draw the line.
References Attempt_7.DrawImageAnalysis::count1D, Attempt_7.DrawImageAnalysis::vertexArray2.
Referenced by Attempt_7.DrawImageAnalysis::AddHoughLinesColor.
void Attempt_7.DrawImageAnalysis.AddHoughLinesColor(double[] houghInfo)
Puts the hough information about the lines in the vertex array.
References Attempt_7.DrawImageAnalysis::houghLineStartandStopVectors, Attempt_7.DrawImageAnalysis::InsertLine, Attempt_7.DrawImageAnalysis::NumberofLinesToFind.
Referenced by Attempt_7.DrawImageAnalysis::BuildVertexArrayforDrawingSmallerNumberofTriangles, Attempt_7.DrawImageAnalysis::UpdateBoolMapto3DRectangle, Attempt_7.DrawImageAnalysis::UpdateColorArrayto3DRectangle.
void Attempt_7.DrawImageAnalysis.drawUsingSmallerNumberofVertexs()
References Attempt_7.DrawImageAnalysis::basicEffects, Attempt_7.DrawImageAnalysis::count1D, Attempt_7.DrawImageAnalysis::vertexArray2.
Referenced by Attempt_7.DrawImageAnalysis::Draw.
void Attempt_7.DrawImageAnalysis.DrawText(int turnIndication, int totalWhiteCnt, double[] houghInfo)
Draws the Text giving important information about the status of the analysis.
References Attempt_7.DrawImageAnalysis::arial, Attempt_7.DrawImageAnalysis::count1D, Attempt_7.ImageAnalysis::GetHoughMode, Attempt_7.ImageAnalysis::GetSingularitesOldHough, Attempt_7.ImageAnalysis::GetSingularitiesNewHough, Attempt_7.DrawImageAnalysis::imageAnalysis, Attempt_7.DrawImageAnalysis::NumberofLinesToFind, Attempt_7.DrawImageAnalysis::RhoIncrement, Attempt_7.DrawImageAnalysis::spriteBatch, Attempt_7.DrawImageAnalysis::ThetaIncrement, Attempt_7.DrawImageAnalysis::UpdateSquareDimForAnalysis, Attempt_7.DrawImageAnalysis::UpdateSquareDimForDrawing.
Referenced by Attempt_7.DrawImageAnalysis::Draw.
void Attempt_7.DrawImageAnalysis.LoadVertexArray()
Loads the position of each triangle into the VertexArray.
References Attempt_7.DrawImageAnalysis::basicEffects, Attempt_7.DrawImageAnalysis::camera, Attempt_7.Camera::Projection, Attempt_7.DrawImageAnalysis::screenHeight, Attempt_7.DrawImageAnalysis::screenWidth, Attempt_7.DrawImageAnalysis::vertexArray, Attempt_7.Camera::View, Attempt_7.Camera::World.
Referenced by Attempt_7.DrawImageAnalysis::Initialize.