Attempt_7::Robot
Vector3 Attempt_7.Robot.position
Position of the robot.
Referenced by Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::GetPosition, Attempt_7.Robot::Robot, Attempt_7.Robot::SetPosition, Attempt_7.Robot::SetStartPosition, Attempt_7.Robot::Update.
Vector3 Attempt_7.Robot.startPosition
Where the robot starts. Needed so it can be reset.
Referenced by Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::SetStartPosition.
Vector3 Attempt_7.Robot.direction
Direction the robot is heading.
Referenced by Attempt_7.Robot::ChangeDirection, Attempt_7.Robot::GetDirection, Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::Robot, Attempt_7.Robot::Update.
float Attempt_7.Robot.speed
Speed the robot is moving forward on update. /.
Referenced by Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::Robot, Attempt_7.Robot::Update.
float Attempt_7.Robot.distanceToCameraTarget
The distance in front of the robot that the camera is pointed at.
Referenced by Attempt_7.Robot::Robot.
float Attempt_7.Robot.cameraHeight
Height of the camera above the robot.
Referenced by Attempt_7.Robot::Robot, Attempt_7.Robot::Update.
Camera Attempt_7.Robot.robotCameraView
Camera associated with the robot.
Referenced by Attempt_7.Robot::GetRobotCamera, Attempt_7.Robot::Robot, Attempt_7.Robot::Update.
bool Attempt_7.Robot.paused
Is the robot moving on each all to update? if paused = true then moving, if false then not moving.
Referenced by Attempt_7.Robot::GetIsRobotPaused, Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::Initialize, Attempt_7.Robot::Update.
int Attempt_7.Robot.changeDirectionThreshholdValue
How big does the turn indicator have to be, before the robot turns. 20 is default.
Referenced by Attempt_7.Robot::ChangeDirection.
int Attempt_7.Robot.timePressedKey
Time in total milliseconds from the start of the game to the last time one of the keys was pressed.
Referenced by Attempt_7.Robot::GetKeyBoard.
Attempt_7.Robot.Robot(Game game, Vector3 position, Vector3 direction, float speed, float howFarToLookInFront, float cameraHeight)
Initializes a new instance of the Robot class.
game The game associate with the robot. position Where the robot is to start direction What direction the robot is pointed at speed How fast the robot will go. howFarToLookInFront How far in front of the robot the camera is to point. cameraHeight How high above the ground the camera for the robot is.
References Attempt_7.Robot::cameraHeight, Attempt_7.Robot::direction, Attempt_7.Robot::distanceToCameraTarget, Attempt_7.Robot::position, Attempt_7.Robot::robotCameraView, Attempt_7.Robot::speed.
Vector3 Attempt_7.Robot.GetPosition()
Gets the current position of the Robot.
Vector3 value of the robot position
References Attempt_7.Robot::position.
Referenced by Attempt_7.SimulationMain::UpDateRobotPosition.
void Attempt_7.Robot.SetPosition(Vector3 pos)
Sets the position of the robot.
pos The new position of the robot.
References Attempt_7.Robot::position.
void Attempt_7.Robot.SetStartPosition(Vector3 pos)
Called when the robot is first placed. Stores the value of the start position so that the robot can be reset to this location.
pos The position of the robot when it starts.
References Attempt_7.Robot::position, Attempt_7.Robot::startPosition.
Referenced by Attempt_7.SimulationMain::LoadLines.
Camera Attempt_7.Robot.GetRobotCamera()
Gets the camera/view that the robot's camera sees.
The camera associated with the robot.
References Attempt_7.Robot::robotCameraView.
Referenced by Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::UpDateRobotPosition.
bool Attempt_7.Robot.GetIsRobotPaused()
Accessor method that tells if the robot is moving forward.
True if paused, false if robot is moving.
References Attempt_7.Robot::paused.
Referenced by Attempt_7.SimulationMain::DrawText, Attempt_7.SimulationMain::UpDateRobotPosition.
Vector3 Attempt_7.Robot.GetDirection()
Accessor method that tells the direction the robot is going.
Vector3 of the direction the robot is pointed
References Attempt_7.Robot::direction.
override void Attempt_7.Robot.Initialize()
Called when the robot object is first made. The robot starts paused.
References Attempt_7.Robot::paused.
void Attempt_7.Robot.ChangeDirection(float turnIndicator)
Turns the robot based on the value of the turnIndicator Turn indicator must be greater or less than the threshold turn value before the robot will turn. Positive cross product of positive z with the dirrection the robot is going = "right" Negative cross product of positive z with the dirrection the robot is going = "left"
turnIndicator The TurnIndicator value must be passed to this method
References Attempt_7.Robot::changeDirectionThreshholdValue, Attempt_7.Robot::direction.
Referenced by Attempt_7.SimulationMain::UpDateRobotPosition.
override void Attempt_7.Robot.Update(GameTime gameTime)
Main Update method. Calls all other methods for updating the robot. Because the robot is a GameComponent, the update method is called by the Game1.update method.
gameTime Clock information
References Attempt_7.Robot::cameraHeight, Attempt_7.Robot::direction, Attempt_7.Robot::GetKeyBoard, Attempt_7.Robot::paused, Attempt_7.Robot::position, Attempt_7.Robot::robotCameraView, Attempt_7.Camera::SetCameraPositionAndTarget, Attempt_7.Robot::speed, Attempt_7.Camera::Update.
void Attempt_7.Robot.GetKeyBoard(GameTime gameTime1)
Checks to see if a key was pressed. F1,F2,Numpad4,NumPad6,NumPad8,NumPad2 are all checked. Called by update.
gameTime1 Clock information
References Attempt_7.Robot::direction, Attempt_7.Robot::paused, Attempt_7.Robot::position, Attempt_7.Robot::speed, Attempt_7.Robot::startPosition, Attempt_7.Robot::timePressedKey.
Referenced by Attempt_7.Robot::Update.