Attempt_7::Camera
Matrix Attempt_7.Camera.View
Matrix representation of the view determined by the position, target, and updirection.
Referenced by Attempt_7.Camera::Camera, Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::DrawRobot, Attempt_7.DrawImageAnalysis::LoadVertexArray, Attempt_7.Camera::Update.
Matrix Attempt_7.Camera.Projection
Matrix representation of the view determined by the angle of the field of view (Pi/4), aspectRatio, nearest plane visible (1), and farthest plane visible (1200)
Referenced by Attempt_7.Camera::Camera, Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::DrawRobot, Attempt_7.DrawImageAnalysis::LoadVertexArray.
Matrix Attempt_7.Camera.World
Matrix representing how the real world cordinates differ from that of the rendering by the camera.
Referenced by Attempt_7.Camera::Camera, Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::DrawRobot, Attempt_7.DrawImageAnalysis::LoadVertexArray.
Vector3 Attempt_7.Camera.cameraPosition
The position of the camera. Defualt = 0,0,0.
Referenced by Attempt_7.Camera::Camera, Attempt_7.Camera::GetCameraPosition, Attempt_7.Camera::SetCameraPositionAndTarget, Attempt_7.Camera::Update.
Vector3 Attempt_7.Camera.target
Target of the camera = a point in 3D space that the camera is pointed at.
Referenced by Attempt_7.Camera::Camera, Attempt_7.Camera::SetCameraPositionAndTarget, Attempt_7.Camera::Update, Attempt_7.Camera::UpdateKeyBoard.
Vector3 Attempt_7.Camera.updirection
The 3D vector that defines which direction is up for the camera.
Referenced by Attempt_7.Camera::Camera, Attempt_7.Camera::Update.
Vector3 Attempt_7.Camera.mouseOffset
If the camera is mouse controlled, how much should the mouse cordinates differ from 3D cordinates in space. How much should they be translated in 3D space.
Referenced by Attempt_7.Camera::Camera, Attempt_7.Camera::UpdateKeyBoard.
bool Attempt_7.Camera.isMouseDependent
If the camera is mouse dependent than the position of the mouse determines the position of the camera in 3D space.
Referenced by Attempt_7.Camera::Camera, Attempt_7.Camera::Update.
Attempt_7.Camera.Camera(Game game, Vector3 pos, Vector3 target, Vector3 up, bool isMouseDependent)
Initializes a new instance of the Camera class.
game The game object of the simulation pos The start position of the camera in 3D space target A point in 3D space that the camera will point at. up The 3D vector that determines which direction is up for the camera isMouseDependent Sets the camera's position based on the mouse if true
References Attempt_7.Camera::cameraPosition, Attempt_7.Camera::isMouseDependent, Attempt_7.Camera::mouseOffset, Attempt_7.Camera::Projection, Attempt_7.Camera::target, Attempt_7.Camera::updirection, Attempt_7.Camera::View, Attempt_7.Camera::World.
override void Attempt_7.Camera.Initialize()
Initializes the camera.
override void Attempt_7.Camera.Update(GameTime gameTime)
Updates the camera's view. If the camera is mouse dependent than Update gets the position of the mouse and keyboard inorder to update the camera position.
gameTime Clock Information
References Attempt_7.Camera::cameraPosition, Attempt_7.Camera::isMouseDependent, Attempt_7.Camera::target, Attempt_7.Camera::UpdateKeyBoard, Attempt_7.Camera::UpdateMouse, Attempt_7.Camera::updirection, Attempt_7.Camera::View.
Referenced by Attempt_7.Robot::Update.
Vector3 Attempt_7.Camera.GetCameraPosition()
Returns the current camera position in 3D space.
The camera position
References Attempt_7.Camera::cameraPosition.
void Attempt_7.Camera.SetCameraPositionAndTarget(Vector3 pos, Vector3 target)
Sets the camera position and target point to a specific position.
pos The new position of the camera in 3D space target The new target point of the camera in 3D space
References Attempt_7.Camera::cameraPosition, Attempt_7.Camera::target.
Referenced by Attempt_7.Robot::Update.
void Attempt_7.Camera.UpdateMouse()
Updates the position of the camera based on the mouse's position. The Mouse origin (0,0) is the top left corner of the simulation Window.
Referenced by Attempt_7.Camera::Update.
void Attempt_7.Camera.UpdateKeyBoard()
Checks to see if the Arrow keys are pressed. Moves the camera position and target based on the arrow keys.
References Attempt_7.Camera::mouseOffset, Attempt_7.Camera::target.
Referenced by Attempt_7.Camera::Update.