Attempt_7::SimulationMain
GraphicsDeviceManager Attempt_7.SimulationMain.graphics
GPU manager.
Referenced by Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::SimulationMain.
Vector2 Attempt_7.SimulationMain.screenSize
2D vector representing the resolution of the cameras used in the simulation.
Referenced by Attempt_7.SimulationMain::BuildRenderTargets, Attempt_7.SimulationMain::Initialize.
Rectangle Attempt_7.SimulationMain.screenRectangle
Rectangle object that is the size of the camera resolution (screenSize).
Vector2 Attempt_7.SimulationMain.windowSize
2D vector represeting the size of the Window's Window that the simulation will run in.
Referenced by Attempt_7.SimulationMain::Initialize.
SpriteBatch Attempt_7.SimulationMain.spriteBatch
The sprite batch object. Used to draw 2D graphics.
Referenced by Attempt_7.SimulationMain::Draw, Attempt_7.SimulationMain::DrawText, Attempt_7.SimulationMain::LoadContent.
Texture2D Attempt_7.SimulationMain.grass
Represents the texture of the grass bitmap that is used to represent the grass.
Referenced by Attempt_7.SimulationMain::LoadContent.
Texture2D Attempt_7.SimulationMain.largeGrass
A large tiled version of the grass Texture.
Referenced by Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::LoadContent.
BasicEffect Attempt_7.SimulationMain.basicEffects
The basicEffects for rendering in 3D.
Referenced by Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::DrawRobot, Attempt_7.SimulationMain::LoadContent.
VertexPositionColor [] Attempt_7.SimulationMain.verts1
The vertexPositionColor array holding the vertex information needed for drawing the white lines representing the course.
Referenced by Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::LoadLines.
VertexPositionTexture [] Attempt_7.SimulationMain.verts2
The vertexPositionColor array holding the information for the grass/ground.
Referenced by Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::LoadGround.
VertexPositionColor [] Attempt_7.SimulationMain.verts3
The vertexPositionColor Array holding the information needed for the 3D representation of the robot.
Referenced by Attempt_7.SimulationMain::DrawRobot, Attempt_7.SimulationMain::UpDateRobotPosition.
List<Viewport> Attempt_7.SimulationMain.viewPortList
List holding the viewports used in the simulation.
Referenced by Attempt_7.SimulationMain::CreateViewPorts, Attempt_7.SimulationMain::Draw, Attempt_7.SimulationMain::Initialize.
bool Attempt_7.SimulationMain.trackRobot
Bool representing if the main Camera moves its view to follow the robot.
Referenced by Attempt_7.SimulationMain::GetKeyBoard, Attempt_7.SimulationMain::UpDateRobotPosition.
int Attempt_7.SimulationMain.timePressedKey
Time in totalmillseconds when F1, F2, or F3 were pushed.
Referenced by Attempt_7.SimulationMain::GetKeyBoard.
SpriteFont Attempt_7.SimulationMain.arialLarge
The 2D font object needed to show text. Size = 20.
Referenced by Attempt_7.SimulationMain::DrawText, Attempt_7.SimulationMain::LoadContent.
SpriteFont Attempt_7.SimulationMain.arialSmall
A smaller font of arial to show debug information.
Referenced by Attempt_7.SimulationMain::LoadContent.
Random Attempt_7.SimulationMain.rand
Represents a random object so that random numbers can be generated.
Referenced by Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::LoadLines.
Robot Attempt_7.SimulationMain.robot1
The robot object. See the robot class for more information.
Referenced by Attempt_7.SimulationMain::DrawText, Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::LoadLines, Attempt_7.SimulationMain::UpDateRobotPosition.
List<Camera> Attempt_7.SimulationMain.cameraList
A list of the cameras. There are 2, The mainview and the robot view. WorldView Camera = 0 (The main camera) Robot View Camera = 1
Referenced by Attempt_7.SimulationMain::Draw, Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::UpDateRobotPosition.
List<RenderTarget2D> Attempt_7.SimulationMain.renderTargets
A list of the rendertargets. Rather than rendering to the screen, the image produced by the GPU is saved to a rendertarget. The rendertargets correspond directly with the camera views. World View Target = 0 Robot View Target = 1
Referenced by Attempt_7.SimulationMain::BuildRenderTargets, Attempt_7.SimulationMain::Draw.
ImageAnalysis Attempt_7.SimulationMain.imageAnalysis
The image analysis object/class does the image processing.
Referenced by Attempt_7.SimulationMain::Draw, Attempt_7.SimulationMain::Initialize, Attempt_7.SimulationMain::UpDateRobotPosition.
int Attempt_7.SimulationMain.currentHoughMode
If 0 then Old mode (top left origin), if 1 then New Hough mode( bottom Center).
Referenced by Attempt_7.SimulationMain::GetKeyBoard.
Attempt_7.SimulationMain.SimulationMain()
Initializes a new instance of the SimulationMain class.
References Attempt_7.SimulationMain::graphics.
override void Attempt_7.SimulationMain.Initialize()
Initialize the Simulation Object.
References Attempt_7.SimulationMain::cameraList, Attempt_7.SimulationMain::CreateViewPorts, Attempt_7.Robot::GetRobotCamera, Attempt_7.SimulationMain::graphics, Attempt_7.SimulationMain::imageAnalysis, Attempt_7.SimulationMain::rand, Attempt_7.SimulationMain::robot1, Attempt_7.SimulationMain::screenSize, Attempt_7.SimulationMain::viewPortList, Attempt_7.SimulationMain::windowSize.
override void Attempt_7.SimulationMain.LoadContent()
Called after initialize. Loads the textures and calls methods to create the simulated enviroment.
References Attempt_7.SimulationMain::arialLarge, Attempt_7.SimulationMain::arialSmall, Attempt_7.SimulationMain::basicEffects, Attempt_7.SimulationMain::CreateGrassTexture, Attempt_7.SimulationMain::grass, Attempt_7.SimulationMain::largeGrass, Attempt_7.SimulationMain::LoadGround, Attempt_7.SimulationMain::LoadLines, Attempt_7.SimulationMain::spriteBatch, Attempt_7.SimulationMain::UpDateRobotPosition.
override void Attempt_7.SimulationMain.UnloadContent()
Unloads Information when the simulation is closed. Currently no information is saved when the simulation is closed.
override void Attempt_7.SimulationMain.Update(GameTime gameTime)
Main update method for the entire simulation. Simulation logic is updated when this method is called. Part of the game loop.
gameTime Clock information
References Attempt_7.SimulationMain::GetKeyBoard, Attempt_7.SimulationMain::UpDateRobotPosition.
void Attempt_7.SimulationMain.GetKeyBoard(GameTime gameTime1)
Checks the keyboard for F3, and Escape.
gameTime1 Clock information
References Attempt_7.SimulationMain::currentHoughMode, Attempt_7.SimulationMain::timePressedKey, Attempt_7.SimulationMain::trackRobot.
Referenced by Attempt_7.SimulationMain::Update.
override void Attempt_7.SimulationMain.Draw(GameTime gameTime)
Main draw method for the simulation. Draws all the world from both the mainview and the robots view. The render target must be built and disposed each time or else the a memory overload will occur.
Each time the Viewport is changed a new spriteBatch.Start method must be called. gameTime Clock Information
References Attempt_7.SimulationMain::BuildRenderTargets, Attempt_7.SimulationMain::cameraList, Attempt_7.SimulationMain::DrawColorLines, Attempt_7.SimulationMain::DrawGrass, Attempt_7.SimulationMain::DrawRobot, Attempt_7.SimulationMain::DrawText, Attempt_7.SimulationMain::DrawTextDebugInfo, Attempt_7.SimulationMain::imageAnalysis, Attempt_7.SimulationMain::renderTargets, Attempt_7.ImageAnalysis::SetRobotCameraView, Attempt_7.SimulationMain::spriteBatch, Attempt_7.ImageAnalysis::Update1, Attempt_7.SimulationMain::viewPortList.
void Attempt_7.SimulationMain.DrawTextDebugInfo()
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.SimulationMain.CreateViewPorts()
Creates the 5 view ports. View ports are like windows inside of a Window's window. MainPort = 0 TopRight = 1 CenterRight = 2 BottomRight = 3 BottomLeft = 4 BottomCenter = 5
References Attempt_7.SimulationMain::viewPortList.
Referenced by Attempt_7.SimulationMain::Initialize.
Texture2D Attempt_7.SimulationMain.CreateGrassTexture(Texture2D texturetoUse)
Takes a texture and returns a larger texture. Size of the new texture is 1024,1024.
texturetoUse The smaller texture to tile The larger texture with the smaller on tiled onto it.
References Attempt_7.SimulationMain::TextureTo2DArray.
Referenced by Attempt_7.SimulationMain::LoadContent.
Color [,] Attempt_7.SimulationMain.TextureTo2DArray(Texture2D texture)
Takes a texture converts it into a 2D color array.
texture The texture to convert The 2D color array
Referenced by Attempt_7.SimulationMain::CreateGrassTexture.
void Attempt_7.SimulationMain.LoadGround()
Create vertex data for the grass. Verts2 is the VertexPositionTexture array.
References Attempt_7.SimulationMain::verts2.
Referenced by Attempt_7.SimulationMain::LoadContent.
void Attempt_7.SimulationMain.LoadLines()
Creates the vertexPositionColor array "verts1" that is used to draw the white lines.
References Attempt_7.SimulationMain::rand, Attempt_7.SimulationMain::robot1, Attempt_7.Robot::SetStartPosition, Attempt_7.SimulationMain::verts1.
Referenced by Attempt_7.SimulationMain::LoadContent.
void Attempt_7.SimulationMain.UpDateRobotPosition()
Loads the vertex information about the robot and recreates it every game cycle to reflect the new position of the robot. 'verts3' is the VertexPositionColor array.
References Attempt_7.SimulationMain::cameraList, Attempt_7.Robot::ChangeDirection, Attempt_7.Robot::GetIsRobotPaused, Attempt_7.Robot::GetPosition, Attempt_7.Robot::GetRobotCamera, Attempt_7.ImageAnalysis::GetTurnIndicator, Attempt_7.SimulationMain::imageAnalysis, Attempt_7.SimulationMain::robot1, Attempt_7.SimulationMain::trackRobot, Attempt_7.SimulationMain::verts3.
Referenced by Attempt_7.SimulationMain::LoadContent, Attempt_7.SimulationMain::Update.
void Attempt_7.SimulationMain.BuildRenderTargets()
Set the renderTargets to a texture object in memory rather than rendering to the screen. Need target for both the Worldview and the robot CameraView.
References Attempt_7.SimulationMain::renderTargets, Attempt_7.SimulationMain::screenSize.
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.SimulationMain.DrawRobot(Camera camera)
Draw the robot from the "camera"s perspective.
camera The camera to use when drawing.
References Attempt_7.SimulationMain::basicEffects, Attempt_7.Camera::Projection, Attempt_7.SimulationMain::verts3, Attempt_7.Camera::View, Attempt_7.Camera::World.
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.SimulationMain.DrawColorLines(Camera camera)
Draw the lines from the "camera"'s persepective.
camera The camera to use when drawing.
References Attempt_7.SimulationMain::basicEffects, Attempt_7.Camera::Projection, Attempt_7.SimulationMain::verts1, Attempt_7.Camera::View, Attempt_7.Camera::World.
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.SimulationMain.DrawGrass(Camera camera)
Draw the grass or ground from "camera"'s perspective.
camera The camera to use when drawing.
References Attempt_7.SimulationMain::basicEffects, Attempt_7.SimulationMain::largeGrass, Attempt_7.Camera::Projection, Attempt_7.SimulationMain::verts2, Attempt_7.Camera::View, Attempt_7.Camera::World.
Referenced by Attempt_7.SimulationMain::Draw.
void Attempt_7.SimulationMain.DrawText()
Draw the Simulation Status as either PAUSED or Active.
References Attempt_7.SimulationMain::arialLarge, Attempt_7.Robot::GetIsRobotPaused, Attempt_7.SimulationMain::robot1, Attempt_7.SimulationMain::spriteBatch.
Referenced by Attempt_7.SimulationMain::Draw.